// 예시

export const signUpUser_Query = () => {
  return `INSERT INTO MEMBER (USER_ID, USER_PW, CUST_NO, NAME, TEL, REG_DT, ADDRESS, EMAIL, BIRTHDAY) VALUES (:USER_ID, :USER_PW, :CUST_NO, :NAME, :TEL, SYSDATE, :ADDRESS, :EMAIL, :BIRTHDAY)`;
}



export const checkSeq_Query = () => {
  return `SELECT MAX(NVL(SEQ, 0)) AS SEQ FROM PCITYDEV.CM_TBO_CUSTGAME_DET WHERE SALES_DATE=:SALES_DATE AND TBL_CD=:TBL_CD AND SEAT_NO=:SEAT_NO AND GAMEEND_DTIME IS NOT NULL AND C_CUST_NO=:C_CUST_NO`;
}


export const uploadBetInfo_Query = () => {
  return `INSERT INTO TEST.RFID_BET_INFO (BRANCH_CD, C_CUST_NO, SALES_DATE, SEQ, TBL_CD, SEAT_NO, REG_DTIME, PLAY_BET, BANKER_BET, TIE_BET, PAIR_BET, LUCKY_BET) VALUES(:BRANCH_CD, :C_CUST_NO, :SALES_DATE, :SEQ, :TBL_CD, :SEAT_NO, SYSDATE, :PLAY_BET, :BANKER_BET, :TIE_BET, :PAIR_BET, :LUCKY_BET)`;
}


