// 예시

export const signUpUser_Query = () => {
  //return `INSERT INTO MEMBER (USER_ID, USER_PW, CUST_NO, NAME, TEL, REG_DT, ADDRESS, EMAIL, BIRTHDAY) VALUES (:USER_ID, :USER_PW, :CUST_NO, :NAME, :TEL, SYSDATE, :ADDRESS, :EMAIL, :BIRTHDAY)`;
  return `INSERT INTO MEMBER SET ?`;
}

