// 예시


export const checkSalesDate_Query = () => {
  //return `SELECT * FROM TEST.CM_SPT_DAY_CLOSE WHERE CLOSE_JOB_KIND = 1 AND TO_CHAR(SYSDATE, 'YYYYmmDD')-1 = CLOSE_DATE`;
  return `SELECT * FROM TEST.CM_SPT_DAY_CLOSE WHERE CLOSE_JOB_KIND = 1 AND CLOSE_DATE='20230223'`;
}

// 0769213
export const checkCustNo_Query = () => {
  //return `SELECT C_CUST_NO, MAX(NVL(SEQ, 0)) AS SEQ FROM PCITYDEV.CM_TBO_CUSTGAME_DET WHERE SALES_DATE=:SALES_DATE AND TBL_CD=:TBL_CD AND SEAT_NO=:SEAT_NO AND GAMEEND_DTIME IS NOT NULL GROUP BY C_CUST_NO`;
  return `SELECT * FROM PCITYDEV.CM_TBO_CUSTGAME_DET WHERE SALES_DATE=:SALES_DATE AND TBL_CD=:TBL_CD AND SEAT_NO=:SEAT_NO AND GAMEEND_DTIME IS NOT NULL ORDER BY GAMEEND_DTIME DESC`;
}

export const checkSeq_Query = () => {
  return `SELECT MAX(NVL(SEQ, 0)) AS SEQ FROM PCITYDEV.CM_TBO_CUSTGAME_DET WHERE SALES_DATE=:SALES_DATE AND TBL_CD=:TBL_CD AND SEAT_NO=:SEAT_NO AND GAMEEND_DTIME IS NOT NULL AND C_CUST_NO=:C_CUST_NO`;
}


export const uploadBetInfo_Query = () => {
  return `INSERT INTO TEST.RFID_BET_INFO (BRANCH_CD, C_CUST_NO, SALES_DATE, SEQ, TBL_CD, SEAT_NO, REG_DTIME, PLAY_BET, BANKER_BET, TIE_BET, PAIR_BET, LUCKY_BET) VALUES(:BRANCH_CD, :C_CUST_NO, :SALES_DATE, :SEQ, :TBL_CD, :SEAT_NO, SYSDATE, :PLAY_BET, :BANKER_BET, :TIE_BET, :PAIR_BET, :LUCKY_BET)`;
}


